# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 528548867f5c56b52fe3d273d358a9e87f842c28e676e96ca38d8db93cb6022efcb64937b47d2e668b3a6bce6735457df8e3b9001299797bc29e776ca24c9688

test:
  secret_key_base: 1d4514122c3101ce2c0313c98d7db6bf907eb302f996894821f191b55487ca13878ce21db38016c12809fc82de64f4e46c8b854314140bf6dbf56845c9a8e92d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
